<?php

namespace yunwuxin\oauth\server;

use League\OAuth2\Server\Exception\OAuthServerException;
use Psr\Http\Message\ResponseInterface;

class Exception extends OAuthServerException
{
    public function generateHttpResponse(ResponseInterface $response = null, $useFragment = false, $jsonOptions = 0)
    {
        if (!$response) {

        }
        return parent::generateHttpResponse($response, $useFragment, $jsonOptions); // TODO: Change the autogenerated stub
    }
}
